/* empty css                      */import{S as q,a as R,i as a}from"./assets/vendor-DceEIEvX.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&d(u)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const m=document.querySelector("#gallery");let f;function y(t){const o=t.map(r=>`<li class="photo-card">
        <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}"alt="${r.tags}" loading="lazy"/></a>
        <div class="info">
        <p><b>Likes:</b>${r.likes}</p>
        <p><b>Views:</b>${r.views}</p>
        <p><b>Comments:</b>${r.comments}</p>
        <p><b>Downloads:</b>${r.downloads}</p>
        </div>
        </li>`).join("");m.insertAdjacentHTML("beforeend",o)}function g(){m.innerHTML=""}function b(){f?f.refresh():f=new q(".gallery a")}const L=document.querySelector("#loader");function w(){L.classList.remove("hidden")}function c(){L.classList.add("hidden")}const P="51403258-27516aac232bd579eeef49dc1",M="https://pixabay.com/api/";async function v(t,o=1,r=40){return(await R.get(M,{params:{key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:r}})).data}const $=document.querySelector("#search-form");document.querySelector("#gallery");const p=document.querySelector("#load-more-btn");let i=1,l="",h=0;$.addEventListener("submit",async t=>{if(t.preventDefault(),l=t.target.elements.searchQuery.value.trim(),!l){g(),n(),c();return}i=1,g(),n(),w();try{const o=await v(l,i),r=o.hits;if(r.length===0){a.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),c(),n();return}y(r),b(),h=Math.ceil(o.totalHits/40),i<h?S():n()}catch{a.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{c()}});p.addEventListener("click",async()=>{i+=1,n(),w();try{const t=await v(l,i);if(t.hits.length===0){a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),n();return}y(t.hits),b(),O(),i>=h?(a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),n()):S()}catch{a.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{c()}});function S(){p.classList.remove("hidden")}function n(){p.classList.add("hidden")}function O(){const t=document.querySelector(".gallery li");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
